### ISSUE TITLE
How to add support to HTTP Basic Authentication?

### ISSUE THREAD

**Issue by default-writer** [ralscha/eds-starter6-jpa#1]
I have a JSON web-service located at var serverUrl = 'http://localhost:60001/', with login function 'login', and 'logout', which recieves a pair { 'username': <...>, 'password': <...> } and relurn username with user GUID token from database { 'id_token':<...> }

I understand that in 

```
    Ext.Ajax.on('beforerequest', function(conn, options, eOpts) {
        options.withCredentials = true;
    }, this);
    // </debug>

    Ext.Ajax.setDefaultHeaders({
        'X-CSRF-TOKEN': Ext.util.Cookies.get("X-CSRF-TOKEN")
    });
```

I must provide information like default heder info like {'Authorization' : 'Basic ' + authdata} where authdata is Base64 encoded string value <username>:<password>, and, additionally pass it as 'POST' request data. There is no beat service on a server just serverUrl + 'auth'

How can I modify your sources to enable such scenario?

**Comment by ralscha** [comment]
Unfortunately I don't have any experience with Basic authentication. 

The setDefaultHeaders call allows you to set http headers that are added to each request and the beforerequest listener allows you to do some work before the request is sent to the server.

I guess you have to add the header to the setDefaultHeaders call.

```
Ext.Ajax.setDefaultHeaders({
       'X-CSRF-TOKEN': Ext.util.Cookies.get("X-CSRF-TOKEN"),
        'Authorization': 'Basic ' + authdata
});
```
