### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by kernelogic** [ralscha/eds-starter6-jpa#2]
INFO 19/09/16 2:51 PM: liquibase: Successfully acquired change log lock
INFO 19/09/16 2:51 PM: liquibase: Creating database history table with name: PUBLIC.DATABASECHANGELOG
INFO 19/09/16 2:51 PM: liquibase: Reading from PUBLIC.DATABASECHANGELOG
INFO 19/09/16 2:51 PM: liquibase: classpath:/db/changelog.xml: db/1.xml::1::dev: Table app_user created
INFO 19/09/16 2:51 PM: liquibase: classpath:/db/changelog.xml: db/1.xml::1::dev: ChangeSet db/1.xml::1::dev ran successfully in 8ms
INFO 19/09/16 2:51 PM: liquibase: classpath:/db/changelog.xml: db/1.xml::2::dev: Table persistent_login created
INFO 19/09/16 2:51 PM: liquibase: classpath:/db/changelog.xml: db/1.xml::2::dev: ChangeSet db/1.xml::2::dev ran successfully in 2ms
INFO 19/09/16 2:51 PM: liquibase: Successfully released change log lock
[2m2016-09-19 14:51:05.644[0;39m [33m WARN[0;39m [35m9378[0;39m [2m---[0;39m [2m[           main][0;39m [36mationConfigEmbeddedWebApplicationContext[0;39m [2m:[0;39m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'startup' defined in file [/Users/feiya200/Downloads/eds-starter6-jpa-master/target/classes/ch/rasc/eds/starter/config/Startup.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'securityConfig': Unsatisfied dependency expressed through method 'configureGlobal' parameter 2: Error creating bean with name 'passwordEncoder': Requested bean is currently in creation: Is there an unresolvable circular reference?; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'passwordEncoder': Requested bean is currently in creation: Is there an unresolvable circular reference?; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfig': Unsatisfied dependency expressed through method 'configureGlobal' parameter 2: Error creating bean with name 'passwordEncoder': Requested bean is currently in creation: Is there an unresolvable circular reference?; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'passwordEncoder': Requested bean is currently in creation: Is there an unresolvable circular reference?
[2m2016-09-19 14:51:05.677[0;39m [31mERROR[0;39m [35m9378[0;39m [2m---[0;39m [2m[           main][0;39m [36mo.s.b.d.LoggingFailureAnalysisReporter  [0;39m [2m:[0;39m 

---

APPLICATION FAILED TO START

---

Description:

There is a circular dependency between 2 beans in the application context:
    - startup defined in file [/Users/feiya200/Downloads/eds-starter6-jpa-master/target/classes/ch/rasc/eds/starter/config/Startup.class]
    - securityConfig
    - passwordEncoder

**Comment by ralscha** [comment]
Hello

I cannot reproduce this issue with the latest code. 
But one thing you can try is moving the PasswordEncoder to another configuration class

Remove the PasswordEncoder in the class
ch.rasc.eds.starter.config.security.SecurityConfig

```
    /* DELETE THIS
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder(12);
    }
    */
```

then create a new configuration class.

```
package ch.rasc.eds.starter.config;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

@Configuration
public class PasswordEncoderConfiguration {

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder(12);
    }

}

```

**Comment by kernelogic** [comment]
Works for me! Thanks a lot!
