### ISSUE TITLE
How to install ext js library?

### ISSUE THREAD

**Issue by kernelogic** [ralscha/eds-starter6-jpa#3]
Is it mvn install?

I'm getting this error though:
[WRN] Failed to resolve package ext@6.2.0.981
[ERR] Cannot satisfy requirements for "ext"!
[INF]    The following versions are available:
[INF]       5.0.0.970 ( ... compatible back to 4.0)
[INF]       5.0.1.1255 ( ... compatible back to 4.0)
[INF]       5.1.0.107 ( ... compatible back to 4.0)
[INF]       5.1.1.451 ( ... compatible back to 4.0)
[INF]       6.0.0.640 ( ... compatible back to 6.0.0)
[ERR]    The following versions cannot be satisfied:
[ERR]       core: ext@6.2.0.981 (No matches!)
[ERR] 
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExVersion: Cannot resolve package requirements

**Comment by ralscha** [comment]
Hello

Here are the steps to build the project

Download and install Sencha Cmd 6.2.0. Make sure the command sencha is in the system path
https://www.sencha.com/products/extjs/cmd-download/
- clone the project
- `cd eds-starter6-jpa\client`
- `sencha ant init.ext`
- `cd ..`
- `mvn package`
