### ISSUE TITLE
lost some entities?

### ISSUE THREAD

**Issue by huanle0610** [ralscha/eds-starter6-jpa#4]
import ch.rasc.eds.starter.entity.QPersistentLogin;
import ch.rasc.eds.starter.entity.QUser;

not those entities in this path: [https://github.com/ralscha/eds-starter6-jpa/tree/master/src/main/java/ch/rasc/eds/starter/entity](https://github.com/ralscha/eds-starter6-jpa/tree/master/src/main/java/ch/rasc/eds/starter/entity)

**Comment by ralscha** [comment]
Hi

These classes are generated by an annotation processing tool.


`./mvnw generate-sources` 
After this command you should see the classes in the target/generated-sources directory
